"""add service jobs

Revision ID: afb65023f57e
Revises: e2159db2e462
Create Date: 2026-09-11 08:28:33.618430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb65023f57e'
down_revision: Union[str, Sequence[str], None] = 'e2159db2e462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('appointment_id', sa.String(), nullable=True),
    sa.Column('job_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('quoted_amount', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_jobs_appointment_id'), 'service_jobs', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_service_jobs_business_id'), 'service_jobs', ['business_id'], unique=False)
    op.create_index(op.f('ix_service_jobs_created_at'), 'service_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_jobs_customer_id'), 'service_jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_jobs_employee_id'), 'service_jobs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_service_jobs_job_number'), 'service_jobs', ['job_number'], unique=True)
    op.create_index(op.f('ix_service_jobs_priority'), 'service_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_service_jobs_scheduled_end'), 'service_jobs', ['scheduled_end'], unique=False)
    op.create_index(op.f('ix_service_jobs_scheduled_start'), 'service_jobs', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_service_jobs_service_id'), 'service_jobs', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_jobs_status'), 'service_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_jobs_status'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_service_id'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_scheduled_start'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_scheduled_end'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_priority'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_job_number'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_employee_id'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_customer_id'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_created_at'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_business_id'), table_name='service_jobs')
    op.drop_index(op.f('ix_service_jobs_appointment_id'), table_name='service_jobs')
    op.drop_table('service_jobs')
    # ### end Alembic commands ###
